### ISSUE TITLE
Prometheus - undefined label

### ISSUE THREAD

**Issue by ajohnstone** [grafana/grafana-plugins#31]
When a label is not defined for all returned data, the grafana throws an error.

My query could be expressed slightly differently... prometheus handles theses issues correctly.
```
sum(container_cpu_usage_seconds_total{com_docker_compose_service=~".+"}) by (com_docker_compose_project,com_docker_compose_service,image)
```
```
Message:
			com_docker_compose_service is not defined
		
Stack trace:
			ReferenceError: com_docker_compose_service is not defined
    at eval (eval at ec (http://localhost:3000/app/app.d8980bc2.js:9:28630), <anonymous>:6:11)
    at createMetricLabel (http://localhost:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1437658602757:211:24)
    at transformMetricData (http://localhost:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1437658602757:191:21)
    at http://localhost:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1437658602757:75:27
    at Function.Ya (http://localhost:3000/app/app.d8980bc2.js:9:18634)
    at http://localhost:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1437658602757:74:15
    at Function.Ya (http://localhost:3000/app/app.d8980bc2.js:9:18634)
    at http://localhost:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1437658602757:67:13
    at i (http://localhost:3000/app/app.d8980bc2.js:12:3146)
    at http://localhost:3000/app/app.d8980bc2.js:12:3318
		
```
![prometheus-labels](https://cloud.githubusercontent.com/assets/173567/8854368/7912ccb0-3157-11e5-8415-601f3551b5e0.png)
![prometheus-partial-labels](https://cloud.githubusercontent.com/assets/173567/8854369/791669ba-3157-11e5-804c-ed06766a66bd.png)
![prometheus-js-error-partial-labels](https://cloud.githubusercontent.com/assets/173567/8854445/d86191f6-3157-11e5-96a6-a0dbd545573b.png)

**Comment by mtanda** [comment]
@ajohnstone The error might be caused by legend format string.
I tried to fix it by this commit https://github.com/mtanda/grafana-plugins/commit/55edf525552f2c0278d77c3f2efff4e61bf864f8, simply ignore underscore's template error.
